name: Elixir CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and test ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    runs-on: ubuntu-20.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: '1.10'
            otp: '22.3'
          - elixir: '1.15'
            otp: '25.3'
          - elixir: '1.15'
            otp: '26.0'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependency cache
        uses: actions/cache@v3.3.1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Restore build cache
        uses: actions/cache@v3.3.1
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-
      # - name: Restore plt cache
      #   uses: actions/cache@v3.3.1
      #   id: plt-cache
      #   with:
      #     path: priv/plts
      #     key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-${{ hashFiles('**/mix.lock') }}
      #     restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-plts-
      - name: Install dependencies
        if: steps.deps-cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Compile application
        run: mix compile
      # - name: Create plts
        # if: steps.plt-cache.outputs.cache-hit != 'true'
        # run: |
          # mkdir -p priv/plts
          # mix dialyzer --plt
      # - name: Run static code analysis (dialyzer)
      #   run: mix dialyzer --no-check
      # - name: Run static code analysis (credo)
      #   run: mix credo --strict
      - name: Run tests
        run: mix test
      - name: Run tests and coverage
        if: matrix.elixir == '1.15' && matrix.otp == '26.0'
        run: mix coveralls.github